apiVersion: v1
kind: ConfigMap
metadata: 
  name: snipbal-config
  namespace: redis
data:
  REDIS_SENTINELS: "sentinel-0.sentinel.redis.svc.cluster.local:5000,sentinel-1.sentinel.redis.svc.cluster.local:5000,sentinel-2.sentinel.redis.svc.cluster.local:5000"
  REDIS_MASTER_NAME: "mymaster"
